{
    "openapi": "3.0.0",
    "info": {
        "title": "Spend Little",
        "description": "Essa API foi desenvolvida para manipular Spend Little",
        "contact": {
            "email": "gezerramo@gmail.com"
        },
        "version": "0.1"
    },
    "servers": [
        {
            "url": "https://spendlittle.herokuapp.com/api/v1",
            "description": "API(Production)"
        },
        {
            "url": "http://localhost:8000/api/v1",
            "description": "API(Produção)"
        }
    ],
    "paths": {
        "/account": {
            "post": {
                "tags": [
                    "/account"
                ],
                "summary": "Account",
                "description": "Rota responsavel por criar account!",
                "operationId": "cd73684cb2b781a6453236e15acf82f2",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "name",
                                    "email",
                                    "password",
                                    "level_id"
                                ],
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    },
                                    "address": {
                                        "type": "string"
                                    },
                                    "number": {
                                        "type": "number"
                                    },
                                    "phone": {
                                        "type": "string"
                                    },
                                    "complement": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "name": "Fulano de Tal",
                                    "email": "fulano@gmail.com",
                                    "password": "123456",
                                    "address": "Rua teste ",
                                    "phone": "(73) 988203656",
                                    "number": "18",
                                    "complement": "bloco10ap23"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/account/me": {
            "get": {
                "tags": [
                    "/account"
                ],
                "summary": "Account",
                "description": "Responsible route recover account data!!",
                "operationId": "228c02411f7bff10c6d4197280066e8c",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "patch": {
                "tags": [
                    "/account"
                ],
                "summary": "Account",
                "description": "Rota responsavel por editar conta do usuario logado!",
                "operationId": "d375f0c480fcb91943e1fb98e822f11d",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    },
                                    "address": {
                                        "type": "string"
                                    },
                                    "number": {
                                        "type": "number"
                                    },
                                    "phone": {
                                        "type": "string"
                                    },
                                    "complement": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "name": "Fulano de Tal",
                                    "email": "fulano@gmail.com",
                                    "password": "123456",
                                    "address": "Rua teste ",
                                    "phone": "(73) 988203656",
                                    "number": "18",
                                    "complement": "bloco10ap23"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/account/refresh": {
            "get": {
                "tags": [
                    "/account"
                ],
                "summary": "Account",
                "description": "Responsible route refresh token!",
                "operationId": "5de51af5f3f2e5d9432d86d22610c50a",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/authentication": {
            "post": {
                "tags": [
                    "/authentication"
                ],
                "summary": "authentication",
                "description": "Rota responsavel por se autenticar!",
                "operationId": "4a995107cd220d07545b71572142655f",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "email",
                                    "password"
                                ],
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "email": "fulano@gmail.com",
                                    "password": "123456"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/authentication/token": {
            "get": {
                "tags": [
                    "/authentication"
                ],
                "summary": "Authentication",
                "description": "Responsible route verify token!",
                "operationId": "539378e2567a310cd33bf91ba85fa440",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "202": {
                        "description": "Accepted"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/breads": {
            "get": {
                "tags": [
                    "/breads"
                ],
                "summary": "Bread",
                "description": "Rota responsavel por listar todos tipos de pães!",
                "operationId": "588b5f189447c070afb97178978b9651",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/hamburger": {
            "post": {
                "tags": [
                    "/hamburger"
                ],
                "summary": "Hamburger",
                "description": "Rota responsavel por criar hamburger!",
                "operationId": "d5fdb5f4bcf9b59bbadef9b3a1b4df3a",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "breads_id",
                                    "meats_id",
                                    "users_id",
                                    "status_orders_id"
                                ],
                                "properties": {
                                    "breads_id": {
                                        "type": "number"
                                    },
                                    "meats_id": {
                                        "type": "number"
                                    },
                                    "users_id": {
                                        "type": "number"
                                    },
                                    "status_orders_id": {
                                        "type": "number"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "breads_id": 1,
                                    "meats_id": 1,
                                    "users_id": 1,
                                    "status_orders_id": 1,
                                    "optionals": [
                                        1,
                                        2,
                                        8,
                                        9
                                    ]
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/level": {
            "get": {
                "tags": [
                    "/level"
                ],
                "summary": "level",
                "description": "Rota responsavel por listar todos niveis de acesso!",
                "operationId": "c800496a3b8690600b6a1b0fdbca0e62",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/meats": {
            "get": {
                "tags": [
                    "/meats"
                ],
                "summary": "Meat",
                "description": "Rota responsavel por listar todas carnes!",
                "operationId": "f29445c52c8a9655d1186fdf056a3525",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/optionals": {
            "get": {
                "tags": [
                    "/optionals"
                ],
                "summary": "Optional",
                "description": "Rota responsavel por listar todas opcionais!",
                "operationId": "43dd0472a6f3aebb0692479d93f5d5f7",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/user": {
            "get": {
                "tags": [
                    "/user"
                ],
                "summary": "User",
                "description": "Rota responsavel por listar todos os usuarios!",
                "operationId": "29fe6261905366f57d192d4f07905f87",
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/user/{id}": {
            "get": {
                "tags": [
                    "/user"
                ],
                "summary": "User",
                "description": "Rota responsavel recuperar usuario!",
                "operationId": "4826814dc6639c07a116bb14cc3fced1",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Parameter example",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "patch": {
                "tags": [
                    "/user"
                ],
                "summary": "User",
                "description": "Rota responsavel por editar usuario!",
                "operationId": "418e2b1abf275dae06ef49c5efdbbe98",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Parameter example",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "level_id": {
                                        "type": "number"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "name": "Fulano de Tal",
                                    "email": "fulano@gmail.com",
                                    "level_id": 1
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer"
            }
        }
    },
    "security": [
        []
    ]
}